### PR TITLE
add batch call example to readme.md

### PR DESCRIPTION
**Pull request by fanatid**
Perhaps not the best example, but show what you must do when need batch call.

### CODE REVIEW

**Comment by fanatid** [comment]
fixed

**Comment by fanatid** [comment]
Please, don't merge, I want add better example.

**Comment by fanatid** [comment]
Example updated and I think shows good case of using bitcoind rpc...

**Comment by carnesen** [comment]
That's a great example! I didn't really know how batching worked until now, and I've looked at the code many times. As documentation, we can ditch the outer "run" function wrapper. It'd be prudent to write an automated test that this code actually works too. It also occurs to me that a more important question than "how to batch" is "why to batch". Take the example, for example. The same result could be achieved in far fewer lines without batching. Presumably we'd be advocating for batching (by putting it in the examples) because there's a performance gain. Has anybody done that experiment to see how big of a difference it makes in a case like this? I wouldn't guess it'd be huge just because concurrent http requests are something that Node.js is supposed to be good at. Maybe Bitcoin Core handles batches better or more efficiently somehow?

**Comment by fanatid** [comment]
Node.js good with concurrent http request, but what if you need get many transactions at one time? Says when you starting some application and it requires transactions from mempool and mempool very huge (2k,3k,4k or even more transactions) you get EMFILE error, that means you have many opened file descriptors... batch request solved this problem.
For me batch with batchCallback disgusting, I've idea how improve this, but I think that I must create other issue for discuss.

**Comment by carnesen** [comment]
Cool, thanks for elaborating. As for batchCallback, even just to name it batchCall instead would be an improvement (in both the example and the source code).

**Comment by fanatid** [comment]
Agree, replace to batchCall.
New batch interface suggestion in issue #9

**Pull request merged**
